name: BedWars
version: '${project.version}'
main: me.koba1.bedwars.Main
api-version: '1.18'
authors: [ koba1, adbi20014 ]
description: The worst bedwars plugin
depend:
  - ProtocolLib

commands:
  bedwars:
    aliases: [ bedw, bwars, bw ]
  party:
    aliases: [ p ]
